### ISSUE TITLE
Reviews tasks

### ISSUE THREAD

**Issue by valeriocos** [ria18405/Microtasks#1]
Hi @ria18405 , thank you for sharing your work! I'll have a look at it tomorrow.

In the meanwhile, you can open an issue per microtask with the title `Review Microtask <num>`. The body could be empty or contain anything you want to share (pointers to code or documentation, comments, difficulties found) about the microtask.

Thanks!

**Comment by valeriocos** [comment]
Hi @ria18405 ,

Overall all tasks are in a really good shape! good job!

Some of your work could be useful to complement the documentation at https://github.com/chaoss/grimoirelab-sirmordred/blob/master/Getting-Started.md. Please have a look when you have time, and we can then discuss what could be improved.

Please have also a look at https://github.com/chaoss/grimoirelab-sirmordred/issues/439 if you are looking for ideas to submit PRs to grimoirelab :)

Thanks!

**Comment by ria18405** [comment]
Thank you so much @valeriocos for taking out time to review these tasks. I'll go through your suggestions and will try to improve and build upon it. 

I would certainly want to submit more PRs. Will try to explore and find areas which could be improved and hoping to send more PRs soon!

Thank you :)

**Comment by valeriocos** [comment]
Great, you're welcome @ria18405 ! :)
